### ISSUE TITLE
Take over custom vesync repo?

### ISSUE THREAD

**Issue by micahqcade** [vlebourl/strava#1]
Sorry , I could not find a way tp contact you other than filing an issue in your new repo. I would like to take over the custom vesync repo,  if possible. I use it with my humidifier and other appliances.

**Comment by vlebourl** [comment]
thanks, I just started the transfer process:
![image](https://github.com/vlebourl/strava/assets/5701372/a1064ad7-954d-47a9-b2fc-a087fb66fcce)

**Comment by micahqcade** [comment]
Hi, sorry, I see it started but the repo is still shown as archived. Thoughts? I did not get any notifications or emails.

**Comment by vlebourl** [comment]
I just aborted the transfer, I think for user's continuity, it would actually be better for you to fork the repo and for me to advertise your fork as the new reference. Let me know when it's forked and I'll edit my README

**Comment by micahqcade** [comment]
Thank you , I just forked it and will try my best to continue from where
you left off. Thank you!
